# Generated by Django 4.2.25 on 2025-10-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorija',
            name='vrsta',
            field=models.CharField(max_length=20),
        ),
    ]
